### ISSUE TITLE
Cocoapods compile errors Swift 4.2 Xcode 10.1

### ISSUE THREAD

**Issue by djriefler** [button/button-merchant-ios#10]
I am having trouble compiling the ButtonMerchant pod. I get two errors:

1) "Type 'ASIdentifierManager' does not conform to protocol 'ASIdentifierManagerType'" in the ASIdentifierManagerExtensions.swift file. 

2) Instance member 'system' cannot be used on type 'UserAgent' in the UserAgent.swift file

I've tried the usual process of delete derived data, clean build folder, close Xcode, but nothing has helped.

**Comment by djriefler** [comment]
Solved it:
The problem was my project was using the Objective-C version of Apple's AdSupport framework instead of the swift version. I resolved the issue by navigating to my project settings general tab and in the "Linked Frameworks and Libraries" section removed the AdSupport framework then added it again.

**Comment by djriefler** [comment]
Resolved the issue, in my pod file I had been incorrectly specifying the pod to use Swift 3 instead of Swift 4

**Comment by wessmith** [comment]
Thanks for updating and closing—glad you found a solution! 😄
