### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by trevor-holliday-instacart** [button/button-merchant-ios#114]
Will button be generating a privacy manifest for the data it uses?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by wessmith** [comment]
@trevor-holliday-instacart we added a privacy manifest in [Release 1.7.0](https://github.com/button/button-merchant-ios/releases/tag/1.7.0)

**Comment by crherman7** [comment]
@wessmith unfortunately this conflicts with a local `PrivacyInfo.xcprivacy` that is bundled with the mobile application. It should be under the `resource_bundles`:

```
spec.resource_bundles = {
    'Button_resources' => ['Source/Resources/PrivacyInfo.xcprivacy'],
  }
```

https://guides.cocoapods.org/syntax/podspec.html#osx
