### ISSUE TITLE
Conversion to Swift 5

### ISSUE THREAD

**Issue by bbernberg** [button/button-merchant-ios#36]
Are there plans to upgrade to Swift 5? It would be great to get rid of this warning!

<img width="619" alt="Screen Shot 2019-08-14 at 3 58 42 PM" src="https://user-images.githubusercontent.com/1385086/63052042-6afb0980-beac-11e9-9335-55dbca84b3c8.png">

**Comment by thillsman** [comment]
Agreed.

**Comment by paultopher** [comment]
Should be fixed in the [latest release](https://github.com/button/button-merchant-ios/releases/tag/1.1.2)!

Marking as resolved.

**Comment by thillsman** [comment]
Great, thanks!
