### ISSUE TITLE
ButtonMerchant is not building via Carthage.

### ISSUE THREAD

**Issue by ashishGour007** [button/button-merchant-ios#46]
Hi, I am trying to integrate the buttonMerchant SDK to my iOS App via Carthage. Its not building. After checking the log file its showing the below error : - 

ios/Source/Client.swift:65:42: error: cannot use optional chaining on non-optional value of type '[String : Any]'
                let object = responseDict?["object"] as? [String: Any],
                             ~~~~~~~~~~~~^
CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'ButtonMerchant' from project 'ButtonMerchant')

Note :  Xcode version : 11.4
Carthage : github "button/button-merchant-ios" ~> 1.0

**Comment by ashishGour007** [comment]
log file : 

[carthage-xcodebuild.dPf9oT.log](https://github.com/button/button-merchant-ios/files/4445304/carthage-xcodebuild.dPf9oT.log)

**Comment by paultopher** [comment]
Thanks @ashishGour007! I'll take a look at this and get back to you ASAP.

**Comment by paultopher** [comment]
@ashishGour007 I think I've been able to fix your issue in a branch, can you see if changing the carthage line to
```
github "button/button-merchant-ios" "button/paul/nonoptional_chaining_fix"
```
and see if that's able to fix the build issue? If so, we'll do a formal conversion to Swift 5 and issue a patch release.

cc @sidabs

**Comment by ashishGour007** [comment]
> github "button/button-merchant-ios" "button/paul/nonoptional_chaining_fix"

Thanks for the quick response. I will check and let you know.

**Comment by ashishGour007** [comment]
@paultopher , I have tried with your suggestions but the problem persists. Please see the log file.
I have updated the cart file with your suggestions and hit Carthage update --platform iOS command.
[carthage-xcodebuild.xUAYcE.log](https://github.com/button/button-merchant-ios/files/4448295/carthage-xcodebuild.xUAYcE.log)

**Comment by ashishGour007** [comment]
@paultopher, it builds successfully. Please go ahead with the patch release

**Comment by paultopher** [comment]
Should be fixed in the [latest release](https://github.com/button/button-merchant-ios/releases/tag/1.1.2)!

Marking as resolved.
