### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by thillsman** [button/button-merchant-ios#52]
Hey there, are there any plans for adding Swift Package Manager support? I see there's a Package.swift file, but it's very sparse and doesn't include anything useful for Xcode to pull in the library. Thanks!

**Comment by wessmith** [comment]
@thillsman Thanks for the issue. We just added a new [release 1.3.1](https://github.com/button/button-merchant-ios/releases/tag/1.3.1) with SPM support.

**Comment by thillsman** [comment]
Great, thanks!
