### ISSUE TITLE
Carthage install issues

### ISSUE THREAD

**Issue by AlinaChernenko** [button/button-merchant-ios#6]
Hi!
I was trying to install the framework using carthage (based on instructions from https://developer.usebutton.com/guides/merchants/ios/open-source-merchant-library#add) and
- first of all, the error appeared:
 failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/Button/ButtonMerchant.git/' not found 

- secondly, I tried to use button/button-merchant-ios in carthage file and got this log:
carthage update --platform iOS
*** Fetching button-merchant-ios
*** Checking out button-merchant-ios at "1.0.0"
*** xcodebuild output can be found in /var/folders/d2/q_k5wzj96cjbtzzm1t2vhsnm0000gn/T/carthage-xcodebuild.t6npgv.log
*** Skipped building button-merchant-ios due to the error:
Dependency "button-merchant-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/button/button-merchant-ios/issues/new

Could you please advise how I can install button-merchant-ios framework using carthage (cocoapods is not part of my project)? Thanks.

**Comment by wessmith** [comment]
Fixed in #9
