### ISSUE TITLE
Conforming String: Error impacts dependents

### ISSUE THREAD

**Issue by jsorge** [button/button-merchant-ios#77]
There is an extension on String to conform it to Error (found here: https://github.com/button/button-merchant-ios/blob/0bf903203aa43ad5216dc10742ca058ca955d4f9/Source/Extensions/String%2BError.swift#L26). When your SDK is built as a static framework, this conformance leaks outside of your module and any consumers of the Button SDK who have this conformance in their own codebases will get build errors and the compiler will say that the conformance is duplicated.

This actually is a Swift issue, where a public type declared outside of a module cannot internally conform to another protocol (I filed a Swift bug – https://bugs.swift.org/browse/SR-13485 – and this is not going to be fixed because of the ABI implications).

So, this is a long-winded way of requesting that this conformance be removed in favor of an actual error type that you can throw. The alternate would be to declare this conformance to be public but I think that's a mistake because of the impacts it has on your consumers. Making your own error type would be much friendlier to your users. Thanks!

**Comment by wessmith** [comment]
Thanks @jsorge. I came upon this Swift issue recently looking into something unrelated but didn't make the connection here. Thanks for pointing it out! We'll define our own error.
