### ISSUE TITLE
@objc(Customer) and a conflict with a binary SDK

### ISSUE THREAD

**Issue by KingOfBrian** [button/button-merchant-ios#93]
Hey - We have a runtime issue in our app. An SDK that's binary only uses CoreData and looks for a Customer object by string at runtime. Occasionally it finds the `Order.Customer` object from the ButtonMerchant SDK. I did a quick scan of the code and didn't see any need to modify the objc name. Does anyone know if the removing the `@objc(Customer)` annotation will cause an issue?

**Comment by spnkr** [comment]
I'm also having this problem. Has anyone tried removing `@objc(Customer)` from button-merchant with any success?

**Comment by wessmith** [comment]
Thanks for pointing this out. We've changed the class name to `BTNCustomer` in ObjC and declared an alias `Customer` -> `BTNCustomer` for API compatibility. String lookups for the class `Customer` will no longer find the ButtonMerchant `Customer` class. 

- If you were _using_ the ButtonMerchant `Customer` class in ObjC everything will still compile. 
- If you have a conflicting `Customer` class in ObjC in the same scope you're using the ButtonMerchant `Customer` class, you can `#undef Customer` in that file and replace the ButtonMerchant `Customer` class with `BTNCustomer`
