### ISSUE TITLE
Package fails to build for Xcode 12.5/Swift 5.4

### ISSUE THREAD

**Issue by erikkrietsch** [button/button-merchant-ios#98]
The ButtonMerchant (Carthage) target fails to build via Carthage, with the warning: 

`Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead`

This affects the current release version 1.4.3

**Comment by danl3v** [comment]
@chrismaddern would you be able to help with @erikkrietsch's fix? Thank you!

**Comment by wessmith** [comment]
Thanks! This will go out in 1.4.4

**Comment by danl3v** [comment]
Thank you!
